// Code generated by "stringer -type=ResponseCode"; DO NOT EDIT.

package ssp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-240]
	_ = x[CommandNotKnown-242]
	_ = x[WrongNumberOfParameters-243]
	_ = x[ParameterOutOfRange-244]
	_ = x[CommandCannotBeProcessed-245]
	_ = x[SoftwareError-246]
	_ = x[Fail-248]
	_ = x[KeyNotSet-250]
}

const (
	_ResponseCode_name_0 = "OK"
	_ResponseCode_name_1 = "CommandNotKnownWrongNumberOfParametersParameterOutOfRangeCommandCannotBeProcessedSoftwareError"
	_ResponseCode_name_2 = "Fail"
	_ResponseCode_name_3 = "KeyNotSet"
)

var (
	_ResponseCode_index_1 = [...]uint8{0, 15, 38, 57, 81, 94}
)

func (i ResponseCode) String() string {
	switch {
	case i == 240:
		return _ResponseCode_name_0
	case 242 <= i && i <= 246:
		i -= 242
		return _ResponseCode_name_1[_ResponseCode_index_1[i]:_ResponseCode_index_1[i+1]]
	case i == 248:
		return _ResponseCode_name_2
	case i == 250:
		return _ResponseCode_name_3
	default:
		return "ResponseCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
