// Code generated by "stringer -type=UnitType"; DO NOT EDIT.

package ssp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BanknoteValidator-0]
	_ = x[SMARTPayoutFitted-6]
	_ = x[NoteFloatFitted-7]
}

const (
	_UnitType_name_0 = "BanknoteValidator"
	_UnitType_name_1 = "SMARTPayoutFittedNoteFloatFitted"
)

var (
	_UnitType_index_1 = [...]uint8{0, 17, 32}
)

func (i UnitType) String() string {
	switch {
	case i == 0:
		return _UnitType_name_0
	case 6 <= i && i <= 7:
		i -= 6
		return _UnitType_name_1[_UnitType_index_1[i]:_UnitType_index_1[i+1]]
	default:
		return "UnitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
